language: python
python:
  - "3.6"

services:
  - postgres
env:
  - DJANGO=2.1
install:
  - pip install -r requirements.txt

before_script:
  - export DJANGO_SECRET_KEY=ceci_nest_pas_un_cle
  - export ENVIRONMENT=testing

script:
  - python manage.py test
