FROM python:3.6-alpine

# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# and now all these env variables
ENV DJANGO_ENVIRONMENT development

# add and install requirements
RUN apk update && \
	apk add mysql mysql-client mariadb-dev gcc musl-dev && \
	addgroup mysql mysql && \
	rm -rf /var/cache/apk/*
ADD ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r ./requirements.txt

COPY . /usr/src/app

# run server
CMD python ./manage.py migrate && python ./manage.py runserver
